version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: mtek

  spring-boot-app:
    build:
      context: ./server-app
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  react-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"