export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";
export const GETALL_SUCCESS = " GETALL_SUCCESS";
export const GETALL_FAIL = "GETALL_FAIL";
export const GETONE_SUCCESS = "GETONE_SUCCESS";

export const UPDATE_SUCCESS= "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_TACHE ="CREATE_TACHE";
export const RETRIEVE_TACHES = "RETRIEVE_TACHES";
export const UPDATE_TACHE = "UPDATE_TACHE";
export const DELETE_TACHE = "DELETE_TACHE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
